---
title: "Article counts per year figure"
author: "Fred Boehm"
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

We need a bar plot of counts per year for a search with keywords "Mendelian randomization".

I manually recorded the article counts per year for two searches: 
1. genome-wide association study and 2. mendelian randomization.

```{r}
library(magrittr)
dat <- readxl::read_xlsx(path = "data/publication-counts.xlsx", sheet = "counts")
dat %>%
  ggplot2::ggplot(ggplot2::aes(x = year, y = mrcount)) + ggplot2::geom_bar(stat = "identity")
ggplot2::ggsave("figures/mr-counts.png")
```


```{r}
dat %>%
  ggplot2::ggplot(ggplot2::aes(x = year, y = gwascount)) + ggplot2::geom_bar(stat = "identity")
ggplot2::ggsave("figures/gwas-counts.png")

```

```{r}
dat %>%
  tidyr::pivot_longer(!year) %>%
  dplyr::filter(year != 2022) %>%
  ggplot2::ggplot(ggplot2::aes(x = year, y = value, fill = name)) + 
  ggplot2::geom_bar(stat = "identity", 
                    position=ggplot2::position_dodge()) + 
  ggplot2::scale_fill_manual(labels = c("GWAS", "MR"), values=c('#999999','#E69F00')) + 
  ggplot2::ylab("Annual publication count") + 
  ggplot2::xlab("Year") + 
  ggplot2::guides(fill = ggplot2::guide_legend("Search terms"))
  
ggplot2::ggsave("figures/mr-gwas-counts.png")
```


