---
title: "Mendelian randomization for causal inference in Genome-wide association studies"
author: "Frederick J. Boehm & Xiang Zhou"
date: "`r lubridate::now()`"
bibliography: exported.bib
output: 
  - bookdown::html_document2
  - bookdown::word_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Great interest has developed in inferring causal relationships between complex 
traits in observational human genetics studies. 

Genome-wide association studies (GWAS) present unique opportunities for 
discovery of causal relationships via mendelian randomization.

Methods for Mendelian randomization have appeared at a rapid and accelerating pace since the 
appearance of the first GWAS. 

Now, GWAS and Mendelian randomization for Biobank-scale data offer the possibility
of discovering even more causal relationships among complex traits. The large
sample sizes in biobank studies offer the possibility of uncovering associations of modest strength 
that might be undetectable in smaller sample sizes. 




# Mendelian Randomization with one Instrument

We begin our discussion of Mendelian randomization by considering the simplest case, where there is a single genetic marker and a single outcome variable. Mendelian randomization with one instrument uses a single genetic marker 
as the proxy ("instrument" or "instrumental variable") for the "exposure" and asks 
whether variation in the genotypes at the genetic marker causes variation in the 
"outcome" variable, which is typically a second complex trait. When the genetic marker 
is a single nucleotide polymorphism on an autosome, the cohort is partitioned into three 
classes, two homozygote classes and a single heterozygote class, based on genotypes 
for that marker. When the three assumptions of mendelian randomization are satisfied, 
estimation of the causal effect of the exposure on the outcome is possible. 

The outcome variable can be binary, a count, or a continuous variable. 

## Assumptions of Mendelian Randomization

Three assumptions are central to Mendelian Randomization. Satisfying them is necessary to infer causal effects in a MR study. Careful evaluation of the assumptions is needed in MR studies. Briefly, the first assumption states that the exposure is associated with the outcome. The second requires independence, conditional on the exposure and all measured and unmeasured confounders, between the genetic marker and the outcome. The last of the three assumptions states that the genetic marker is independent of all (measured and unmeasured) confounders of the relationship between exposure and outcome. We next discuss these in more detail and consider their evaluation in MR studies.

If the first assumption, about the association between the genetic marker and the exposure, holds, but this association is weak, then an amplification of biases, such as those due to violations of assumptions 2 and 3, may result [@vanderweele_methodological_2014]. 

The second assumption, often termed the exclusion restriction, can also be stated as 
the need for the genetic marker to affect the outcome only through the exposure. In a 
causal diagram, this means that the only path from the marker to the outcome is that 
containing the exposure.

The third assumption, sometimes called the ____, ensures that ___. 

When the three MR assumptions hold, one may use instrumental variable statistical methods, 
with the genetic marker data, the exposure data, and the outcome data, to estimate and to test the causal effect of the exposure on the outcome. 

## Assumption violations

There are several ways that real data may violate the three MR assumptions. These include ___, ____, and ___. 

Recognition that the assumptions may be violated has inspired methods advances that 
enable assumption relaxations under certain conditions. 

## Statistical models for MR with one instrument and one outcome



## Statistical methods for MR with one instrument and one outcome

The approaches to MR can be classified into two categories: two-stage methods and 
likelihood-based methods. Both two-stage strategies and likelihood-based strategies 
make parametric assumptions for the identification of causal effects [@burgess_review_2017].


Two-stage methods use two regressions. In the first stage, the exposure is regressed on
the instrument to obtain fitted values. In the second stage, the outcome is regressed on the fitted values for the 
exposure, which result from the first regression. Note that the uncertainty in the fitted values of 
the first regression is not considered when performing the second regression.







# Mendelian Randomization with multiple instruments

Recognition of complex traits' diverse genetic architectures has fueled development of MR methods with multiple instruments. 




# Horizontal pleiotropy

Horizontal pleiotropy refers to the presence of multiple pathways from a genetic 
variant to the outcome. One of these multiple pathways may contain the exposure variable.
The fact that there are multiple pathways from the genetic variant to the outcome violates
the MR assumptions. @verbanck_detection_2018 documented widespread horizontal pleiotropy 
in GWAS. This finding motivated the development of MR-PRESSO and inspired 
further research into methods to accommodate horizontal pleiotropy in MR studies [@verbanck_detection_2018].
* What does MR-PRESSO do? What are its limitations?







# Correlated horizontal pleiotropy

@yuan_testing_2020 


# Recent Findings

## Omnigenic MR

Recent research on the omnigenic hypothesis, which posits 
that every SNP's effect on a trait is nonzero, has informed
MR methods development [@Boyle2017]. @wang_mendelian_nodate 
recognized the limitations of previous MR methods in the 
context of the omnigenic hypothesis. To accommodate the possibility
that a trait is influenced by many genome-wide, small effects, 

## Multiple outcomes in MR

Investigators have found that combining information from multiple  related traits can lead to more informative MR results. 

One approach to combining information across traits is to extend the univariate MR statistical methods to their multivariate analogs.

# Applications of MR in GWAS 














# Summary and Outlook





# References

