---
title: "Mendelian randomization for causal inference in Genome-wide association studies"
author: "Frederick J. Boehm"
date: "`r lubridate::now()`"
bibliography: exported.bib
csl: elsevier-with-titles.csl
output: 
  - bookdown::github_document2
  - bookdown::html_document2
  - bookdown::word_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Great interest has developed in inferring causal relationships between complex 
traits in observational human genetics studies. 

Genome-wide association studies (GWAS) present unique opportunities for 
discovery of causal relationships via mendelian randomization.

Methods for Mendelian randomization have appeared at a rapid and accelerating pace since the 
appearance of the first GWAS. 

Now, GWAS and Mendelian randomization for biobank-scale data offer the possibility
of discovering even more causal relationships among complex traits.




# Mendelian Randomization with one Instrument

We begin our discussion of Mendelian randomization by considering the simplest case, where there is a single genetic marker and a single outcome variable.

A MR study can be performed with one sample or two samples.









## Assumptions of Mendelian Randomization

Three assumptions are central to Mendelian Randomization.




## Assumption violations

Several real world settings may give rise to violations of one or more of the three assumptions.


## Statistical models for MR with one instrument and one outcome

Statistical models for MR with one instrument can be formulated as two linear regressions. 




## Statistical methods for MR with one instrument and one outcome

Estimation and testing for unknown parameters proceeds in one of several approaches.

## Sensitivity analysis for MR with one instrument and one outcome

Sensitivity analysis is recommended and widely used in MR studies because of the inability to verify the three MR assumptions.




# Mendelian Randomization with multiple instruments

Recognizing that many genetic markers collectively may affect a trait, investigators 
adapted single-instrument MR methods to accommodate multiple genetic markers. 


# Horizontal pleiotropy

Linkage disequilibrium, which refers to genotype correlations for genetic markers 
that are near each other, manifests as horizontal pleiotropy in MR studies.






# Correlated horizontal pleiotropy





# Recent Findings

## Omnigenic MR


## Multiple outcomes in MR


## MR with summary statistics (Morrison et al.)



# Applications of MR in GWAS 














# Summary and Outlook

1. greater sample sizes and richer, molecular phenotyping will continue to enable 
causal inferences in observational human genetics studies

1. ??Experimental validation in animal models?? PerturbSeq?? CRISPR manipulation of putative causal genes??


1. Robustness to assumptions violations





# References

